package com.bits.scalable.api.hotel.room.entity;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.GeneratedValue;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * @author I583856
 * @date 15/11/24
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor // Required for MongoDB to deserialize objects
@Document(collection = "rooms")
public class Room {

    @Id
    private UUID id; // Generate manually in service layer

    @JsonProperty("hotelId")
    private String hotelId; // Reference to the hotel this room belongs to
    @JsonProperty("roomType")
    private List<RoomType> roomType; // Room types will be added later
    private LocalDate currentDate;

    // Add a constructor for creating Room instances with autogenerated UUID
    public Room(String hotelId, List<RoomType> roomType, LocalDate currentDate) {
        this.id = UUID.randomUUID(); // Automatically generate UUID
        this.hotelId = hotelId;
        this.roomType = roomType;
        this.currentDate = currentDate;
    }
}